// Generated by Lasy AI - https://lasy.ai
'use client';

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";
// Import all available fonts for AI usage
import "../lib/fonts";
import { useEffect } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  useEffect(() => {
    // Inicializar automações quando app carregar
    const userId = localStorage.getItem('current_user_id');
    if (userId) {
      import('@/lib/automations').then(({ initializeAutomations }) => {
        initializeAutomations(userId);
        console.log('🤖 Automações do VEXTOR AI inicializadas!');
      });
    }

    // Registrar Service Worker para PWA
    if ('serviceWorker' in navigator) {
      navigator.serviceWorker
        .register('/sw.js')
        .then((registration) => {
          console.log('✅ Service Worker registrado com sucesso:', registration.scope);
        })
        .catch((error) => {
          console.log('❌ Falha ao registrar Service Worker:', error);
        });
    }

    // Detectar instalação PWA
    window.addEventListener('beforeinstallprompt', (e) => {
      e.preventDefault();
      console.log('💡 PWA pode ser instalado');
      // Armazenar evento para mostrar prompt personalizado depois
      (window as any).deferredPrompt = e;
    });

    // Detectar quando PWA foi instalado
    window.addEventListener('appinstalled', () => {
      console.log('✅ VEXTOR AI instalado como PWA!');
    });
  }, []);

  return (
    <html lang="pt-BR">
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=5, user-scalable=yes" />
        <meta name="description" content="Plataforma inteligente para apostas esportivas com análise baseada em IA" />
        <meta name="theme-color" content="#00E5FF" />
        <meta name="mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
        <meta name="apple-mobile-web-app-title" content="VEXTOR AI" />
        
        {/* PWA Manifest */}
        <link rel="manifest" href="/manifest.json" />
        
        {/* Icons */}
        <link rel="icon" href="/icon.svg" type="image/svg+xml" />
        <link rel="apple-touch-icon" href="/icon-192.png" />
        
        {/* Open Graph / Social */}
        <meta property="og:type" content="website" />
        <meta property="og:title" content="VEXTOR AI - Apostas Inteligentes" />
        <meta property="og:description" content="Plataforma inteligente para apostas esportivas com análise baseada em IA" />
        <meta property="og:image" content="/og-image.png" />
        
        <title>VEXTOR AI - Apostas Inteligentes</title>
        
        <Script src="/lasy-bridge.js" strategy="beforeInteractive" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
